### ISSUE TITLE
example give weird results

### ISSUE THREAD

**Issue by hfdavidyu** [strawlab/best#3]
Hello,

when I run example/smart_drug.py, it gives

[-----------------100%-----------------] 110000 of 110000 complete in 11.1 sec
Traceback (most recent call last):
  File "smart_drug.py", line 27, in <module>
    fig = best.plot.make_figure(M)
  File "/usr/local/lib/python2.7/site-packages/best/plot.py", line 130, in make_figure
    posterior_std1 = M.trace('group1_std')[:]
  File "/usr/local/lib/python2.7/site-packages/pymc/Model.py", line 834, in trace
    return self.db.trace(name, chain)
  File "/usr/local/lib/python2.7/site-packages/pymc/database/base.py", line 373, in trace
    trace = copy.copy(self._traces[name])
KeyError: 'group1_std'

and if I do the M.summary(), it shows the correct means (~ 101) but huge SD (~ hundreds). I am using python 2.7 on OSX. I am wondering what should I do to fix/local the problem?

Sincerely,
David Yu

**Comment by astraw** [comment]
Thanks for the report. I recently discovered that this package has been subsumed into pymc3 (see [here](http://docs.pymc.io/notebooks/BEST.html])). As I think they will do a better job of maintaining the implementation, I intend to put this project into an archival mode.

I am therefore referring you to the implementation in pymc3 and closing this issue.
